#%RAML 1.0 NamedExample
[
    {
        "name": "Salesforce System API",
        "status": "DOWN"
    },
    {
        "name": "SAP System API",
        "status": "UP"
    },
    {
        "name": "Products System API",
        "status": "UP"
    },
    {
        "name": "Inventory System API",
        "status": "DOWN"
    }
]